version: 1
disable_existing_loggers: False
        
formatters:
    standard: 
        format: "%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers: 
    default: 
        level: DEBUG
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: standard
    
    err_console: 
        level: ERROR
        class: logging.StreamHandler
        stream: ext://sys.stderr
        formatter: standard

    syslog_file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_syslog
        maxBytes: 524288000  #500MB
        backupCount: 8
        formatter: standard
        encoding: utf8

    file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_collect_metrics.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8

    err_file:
        level: ERROR
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_collect_metrics_err.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8

    pyucs_file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/pyucs.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8

    statsd_file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_stats.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8

    statsd_err_file:
        level: ERROR
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_stats_err.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8

    parser_file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_parser.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8

    parser_err_file:
        level: ERROR
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_parser_err.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8

    influxd_file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_influx.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8

    influxd_err_file:
        level: ERROR
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_influx_err.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8

    datadog_file:
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_datadog.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8

    datadog_err_file:
        level: ERROR
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/ucs_datadog_err.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8

loggers: 
    __main__: 
        handlers: [default, syslog_file, file, err_file]
        level: INFO
        propagate: False

    pyucs:
        handlers: [pyucs_file, syslog_file, file, err_file]
        level: INFO
        propogate: False

    pyucs.credentials.credential:
        handlers: [default, pyucs_file, syslog_file]
        level: INFO
        propagate: False

    pyucs.influx.client:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file, influxd_file, influxd_err_file]
        level: INFO
        propagate: False

    pyucs.statsd:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file]
        level: INFO
        propagate: False

    pyucs.statsd.collector:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file]
        level: DEBUG
        propagate: False

    pyucs.statsd.parse:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file, parser_file, parser_err_file]
        level: INFO
        propagate: False

    pyucs.ucs:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file]
        level: INFO
        propagate: False

    pyucs.ucs.vlan:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file]
        level: INFO
        propagate: False

    pyucs.ucs.vnic:
        handlers: [default, pyucs_file, syslog_file, statsd_file, statsd_err_file]
        level: INFO
        propagate: False

root: 
    level: INFO
    handlers: [default]

